### ISSUE TITLE
FORCE HLPS Sampling Failing for EPSG:7755

### ISSUE THREAD

**Issue by reva1804** [davidfrantz/force#389]
Hi I'm using FORCE v3.9.02 to do LULCC for a study area in the northwest of India and ran into this problem.

Projection was set to EPSG:7755 (https://epsg.io/7755), and FORCE Level-2 processing and Level-3 time series analysis was done on Landsat 8 data using this projection.  Then sampling was done using text file containing training data, and it repeatedly failed even after changing multiple parameters in the sampling parameter file. Upon inspection of the Level-3 TSA directory, I saw that in the datacube-definition.prj the PROJECTION = line was cut.

That is, instead of 
PROJECTION = PROJCS["WGS 84 / India NSF LCC",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["latitude_of_origin",24],PARAMETER["central_meridian",80],PARAMETER["standard_parallel_1",12.472955],PARAMETER["standard_parallel_2",35.1728044444444],PARAMETER["false_easting",4000000],PARAMETER["false_northing",4000000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","7755"]]

as given in the Level-2 output directory and datacube.defenition file, the Level-3 TSA output directory had

PROJECTION = PROJCS["WGS

and subsequently even after manually correcting the above given datacube definition file to the correct projection, sampling still failed.

Finally the same Level-3 TSA directory was uploaded to another system with FORCE v 3.8.01 with the appropriate parameter file,  and the manually corrected datacube.defenition file, and sampling worked.

Could this be a bug in FORCE v3.9.02?

Attaching the parameter file used for sampling, the older version parameter file used for testing on another system and datacube.defenition files of level2, and level 3 TSA and the FILE_POINT file used on all systems

[samples.txt](https://github.com/user-attachments/files/23604301/samples.txt)

[parameter_sampling_landsat (Copy).prm.txt](https://github.com/user-attachments/files/23604355/parameter_sampling_landsat.Copy.prm.txt)

[datacube-definition_level2.txt](https://github.com/user-attachments/files/23604385/datacube-definition_level2.txt)

[datacube-definition_tsa.txt](https://github.com/user-attachments/files/23604398/datacube-definition_tsa.txt)

[parameter_sampling_older_force_version_(worked).prm.txt](https://github.com/user-attachments/files/23604442/parameter_sampling_older_force_version_.worked.prm.txt)

_Error was produced after running_

birdlab@birdlab-Precision-Tower-5810:~$ sudo docker run -it -v /home/birdlab/Pictures/force2020:/data davidfrantz/force force-higher-level /data/parameter_sampling_landsat.prm
number of processing units: 48
 (active tiles: 48, chunks per tile: 1)

________________________________________
Progress:                        100.00%
Time for I/C/O:           067%/033%/000%
ETA:             00y 00m 00d 00h 00m 00s
________________________________________
________________________________________
Real time:       00y 00m 00d 00h 00m 04s
Virtual time:    00y 00m 00d 00h 00m 06s
Saved time:      00y 00m 00d 00h 00m 02s
Chunk X-ID:           NA      NA       0
________________________________________
Virtual I-time:  00y 00m 00d 00h 00m 04s
Virtual C-time:  00y 00m 00d 00h 00m 02s
Virtual O-time:  00y 00m 00d 00h 00m 00s

________________________________________
I-bound time:    00y 00m 00d 00h 00m 02s
C-bound time:    00y 00m 00d 00h 00m 00s
O-bound time:    00y 00m 00d 00h 00m 00s
________________________________________
data read    (uncompressed): 1.31 GB
data written (uncompressed): 0.00 B
________________________________________
Warning: no input or output detected. If
unintentional, triple-check for mis-
matching entries in
  DIR_MASK
  BASE_MASK
  X_TILE_RANGE
  Y_TILE_RANGE
  FILE_TILE
  SENSORS
  DATE_RANGE
  DOY_RANGE
  OUTPUT_***
and make sure that your input file type
  is one of .dat .bsq .bil .tif .vrt

**Setup**
System where sampling didn't work
- FORCE version 3.9.02
Desktop running GNU/Linux OS (Ubuntu 24.04.3 LTS; codename: noble); Dell Precision Tower 5810; Intel® Xeon® E5-1660 v4 × 16; Base speed: 3.2 GHz; 64 GiB RAM; 8 cores; 2 threads per core; 16 logical processors; GPU = NVIDIA Corporation GM206GL [Quadro M2000] (Driver Version: 575.64.03, Dedicated GPU memory: upto 4 GiB); greater than 700 GB free disk space

--Did not deviate from installation instructions

System where sampling worked

- FORCE v 3.8.01
Desktop running Windows 10 OS (later Windows 11); Dell Precision 3660; 13th Gen Intel® Core™ i9-13900; Base speed: 2.00 GHz; 32 GB RAM; 24 cores; 32 logical processors; GPU = i) Intel® UHD Graphics 770 (Driver version: 32.0.101.6881, Driver date: 04-06-2025, DirectX version: 12 (FL 12.1), Dedicated GPU memory: upto 8.0 GB, GPU Memory: upto 15.8 GB) ii) NVIDIA T1000 8GB (Driver version: 32.0.15.7159, Driver date: 31-12-2024, DirectX version: 12 (FL 12.1), Dedicated GPU memory: upto 8.0 GB, GPU Memory: upto 23.8 GB); greater than 1.5 TB free disk space

--Running in WSL2 using podman

**Comment by davidfrantz** [comment]
Thanks for the info, this seems like a bug. I will look into it.

**Comment by davidfrantz** [comment]
Hi @reva1804, thanks for reporting! There has been an oversight in properly handling occasions where whitespaces could be part of the value in a ``TAG = VALUE`` pair. I just pushed a fix for this. Please try version 3.10.03

**Comment by reva1804** [comment]
Hi David,

Thanks for the fix, really appreciate it.

Unfortunately sampling is still not working for me, I re-ran the Level-3 TSA after updating to FORCE v. 3.10.03, and checked the datacube.defenition file generated, everything seems fine, the earlier error had been rectified and PROJECTION was given in full.

However sampling is still failing--

I did not change anything in the sampling parameter file or the samples.txt file given previously, but sampling is still failing---

birdlab@birdlab-Precision-Tower-5810:~$ sudo docker run -it -v /home/birdlab/Pictures/force2020:/data davidfrantz/force force-higher-level /data/parameter_sampling_landsat.prm
Tag-Value pairs :::
Tag: `PROJECTION` Value: `PROJCS["WGS 84 / India NSF LCC",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["latitude_of_origin",24],PARAMETER["central_meridian",80],PARAMETER["standard_parallel_1",12.472955],PARAMETER["standard_parallel_2",35.1728044444444],PARAMETER["false_easting",4000000],PARAMETER["false_northing",4000000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","7755"]]`
Tag: `ORIGIN_GEO_X` Value: `93.957452`
Tag: `ORIGIN_GEO_Y` Value: `29.347729`
Tag: `ORIGIN_MAP_X` Value: `5332728.525252`
Tag: `ORIGIN_MAP_Y` Value: `4647906.806545`
Tag: `TILE_SIZE_X` Value: `30000.000000`
Tag: `TILE_SIZE_Y` Value: `30000.000000`
number of processing units: 48
 (active tiles: 48, chunks per tile: 1)

________________________________________
Progress:                        100.00%
Time for I/C/O:           080%/020%/000%
ETA:             00y 00m 00d 00h 00m 00s
________________________________________
________________________________________
Real time:       00y 00m 00d 00h 00m 04s
Virtual time:    00y 00m 00d 00h 00m 05s
Saved time:      00y 00m 00d 00h 00m 01s
Chunk X-ID:           NA      NA       0
________________________________________
Virtual I-time:  00y 00m 00d 00h 00m 04s
Virtual C-time:  00y 00m 00d 00h 00m 01s
Virtual O-time:  00y 00m 00d 00h 00m 00s

________________________________________
I-bound time:    00y 00m 00d 00h 00m 03s
C-bound time:    00y 00m 00d 00h 00m 00s
O-bound time:    00y 00m 00d 00h 00m 00s
________________________________________
data read    (uncompressed): 1.35 GB
data written (uncompressed): 0.00 B
________________________________________
Warning: no input or output detected. If
unintentional, triple-check for mis-
matching entries in
  DIR_MASK
  BASE_MASK
  X_TILE_RANGE
  Y_TILE_RANGE
  FILE_TILE
  SENSORS
  DATE_RANGE
  DOY_RANGE
  OUTPUT_***
and make sure that your input file type
  is one of .dat .bsq .bil .tif .vrt


Thanks again for responding so quickly:) attaching the updated datacube.definition file

[datacube-definition-updated.prj.txt](https://github.com/user-attachments/files/23621662/datacube-definition-updated.prj.txt)

**Comment by davidfrantz** [comment]
Hmm, can you share the data of one of those tiles?

**Comment by reva1804** [comment]
Sure,

I'm sharing the stats of the blue band and attaching the tile folder contents of X0002_Y-001

[X0002_Y-001.zip](https://github.com/user-attachments/files/23646722/X0002_Y-001.zip)

birdlab@birdlab-Precision-Tower-5810:~$ gdalinfo -stats /home/birdlab/Pictures/force2020/dir_tsa_landsat/X0002_Y-001/20200101-20201231_001-365_HL_TSA_LND08_BLUE_STM.tif

Driver: GTiff/GeoTIFF
Files: /home/birdlab/Pictures/force2020/dir_tsa_landsat/X0002_Y-001/20200101-20201231_001-365_HL_TSA_LND08_BLUE_STM.tif
       /home/birdlab/Pictures/force2020/dir_tsa_landsat/X0002_Y-001/20200101-20201231_001-365_HL_TSA_LND08_BLUE_STM.tif.aux.xml
Size is 1000, 1000
Coordinate System is:
PROJCRS["WGS 84 / India NSF LCC",
    BASEGEOGCRS["WGS 84",
        ENSEMBLE["World Geodetic System 1984 ensemble",
            MEMBER["World Geodetic System 1984 (Transit)"],
            MEMBER["World Geodetic System 1984 (G730)"],
            MEMBER["World Geodetic System 1984 (G873)"],
            MEMBER["World Geodetic System 1984 (G1150)"],
            MEMBER["World Geodetic System 1984 (G1674)"],
            MEMBER["World Geodetic System 1984 (G1762)"],
            MEMBER["World Geodetic System 1984 (G2139)"],
            ELLIPSOID["WGS 84",6378137,298.257223563,
                LENGTHUNIT["metre",1]],
            ENSEMBLEACCURACY[2.0]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        ID["EPSG",4326]],
    CONVERSION["Survey of India Lambert",
        METHOD["Lambert Conic Conformal (2SP)",
            ID["EPSG",9802]],
        PARAMETER["Latitude of false origin",24,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8821]],
        PARAMETER["Longitude of false origin",80,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8822]],
        PARAMETER["Latitude of 1st standard parallel",12.472955,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8823]],
        PARAMETER["Latitude of 2nd standard parallel",35.1728044444444,
            ANGLEUNIT["degree",0.0174532925199433],
            ID["EPSG",8824]],
        PARAMETER["Easting at false origin",4000000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8826]],
        PARAMETER["Northing at false origin",4000000,
            LENGTHUNIT["metre",1],
            ID["EPSG",8827]]],
    CS[Cartesian,2],
        AXIS["easting (X)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["northing (Y)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["NNRMS National Spatial Framework (NSF) state resource database of medium resolution earth observation imagery and mapping."],
        AREA["India - onshore and offshore. Includes Amandivis, Laccadives, Minicoy, Andaman Islands, Nicobar Islands, and Sikkim."],
        BBOX[3.87,65.6,35.51,97.42]],
    ID["EPSG",7755]]
Data axis to CRS axis mapping: 1,2
Origin = (5392728.525251872837543,4677906.806544590741396)
Pixel Size = (30.000000000000000,-30.000000000000000)
Metadata:
  AREA_OR_POINT=Area
Image Structure Metadata:
  COMPRESSION=ZSTD
  INTERLEAVE=BAND
  PREDICTOR=2
Corner Coordinates:
Upper Left  ( 5392728.525, 4677906.807) ( 94d36'50.05"E, 29d33'55.65"N)
Lower Left  ( 5392728.525, 4647906.807) ( 94d34'53.19"E, 29d17'31.76"N)
Upper Right ( 5422728.525, 4677906.807) ( 94d55'34.92"E, 29d32'12.16"N)
Lower Right ( 5422728.525, 4647906.807) ( 94d53'35.60"E, 29d15'48.45"N)
Center      ( 5407728.525, 4662906.807) ( 94d45'13.44"E, 29d24'52.34"N)
Band 1 Block=256x256 Type=Int16, ColorInterp=Gray
  Description = Q25
  Minimum=-523.000, Maximum=14028.000, Mean=7918.302, StdDev=2785.668
  NoData Value=-9999
  Metadata:
    STATISTICS_MAXIMUM=14028
    STATISTICS_MEAN=7918.301650165
    STATISTICS_MINIMUM=-523
    STATISTICS_STDDEV=2785.6682498309
    STATISTICS_VALID_PERCENT=0.606
Band 2 Block=256x256 Type=Int16, ColorInterp=Undefined
  Description = Q50
  Minimum=-523.000, Maximum=14028.000, Mean=7918.324, StdDev=2785.651
  NoData Value=-9999
  Metadata:
    STATISTICS_MAXIMUM=14028
    STATISTICS_MEAN=7918.3237623762
    STATISTICS_MINIMUM=-523
    STATISTICS_STDDEV=2785.6506021083
    STATISTICS_VALID_PERCENT=0.606
Band 3 Block=256x256 Type=Int16, ColorInterp=Undefined
  Description = Q75
  Minimum=-523.000, Maximum=14028.000, Mean=7918.324, StdDev=2785.649
  NoData Value=-9999
  Metadata:
    STATISTICS_MAXIMUM=14028
    STATISTICS_MEAN=7918.3242574257
    STATISTICS_MINIMUM=-523
    STATISTICS_STDDEV=2785.6491905558
    STATISTICS_VALID_PERCENT=0.606

**Comment by davidfrantz** [comment]
Hi @reva1804,

sorry for the late response. I just tested your parameter file and data with the latest FORCE version (3.10.04), executed through Docker.

[coordinates.txt](https://github.com/user-attachments/files/23850919/coordinates.txt)
[features.txt](https://github.com/user-attachments/files/23850918/features.txt)
[response.txt](https://github.com/user-attachments/files/23850920/response.txt)

It works for me, thus it doesn't seem to be a general problem.
